POST http://localhost:4000/api/user/auth/create HTTP/1.1
Content-Type: application/json

{
    "mobile": 1234567891,
    "email": "email@email.com",
    "name": "fksdfkljdskl",
    "password": "1234"
}
###
POST http://localhost:4000/api/user/auth/login HTTP/1.1
Content-Type: application/json

{
    "mobile": 1234567891,
    "password": "1234"
}
###
POST http://localhost:4000/api/user/auth/refresh HTTP/1.1
Content-Type: application/json

{
    "authtoken": 2323,
    "reftoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJGX05BTUUiOiJma3NkZmtsamRza2wiLCJNX05BTUUiOm51bGwsIkxfTkFNRSI6bnVsbCwiTU9CSUxFX05PIjoyMzIzLCJFTUFJTF9JRCI6ImVtYWlsQGVtYWlsLmNvbSIsIlBBUkVOVF9JRCI6bnVsbCwiaWQiOjU1LCJ1c2VyX2lkIjoxNCwiZXhwaXJlc0luIjoiMjAyMi0xMi0wMlQwOToxNjowMi4wMDBaIiwidHlwZSI6MSwiaWF0IjoxNjM4NDM2NTYyLCJleHAiOjE2Njk5OTQxNjJ9.HpqXY71G1TSiUSBC7uDtIRdmzWa3EU7sPzCQjA4mVzQ"
}

###
GET  http://localhost:4000/api/user/auth/check HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJGX05BTUUiOiJma3NkZmtsamRza2wiLCJNX05BTUUiOm51bGwsIkxfTkFNRSI6bnVsbCwiTU9CSUxFX05PIjoyMzIzLCJFTUFJTF9JRCI6ImVtYWlsQGVtYWlsLmNvbSIsIlBBUkVOVF9JRCI6bnVsbCwiaWQiOjU1LCJ1c2VyX2lkIjoxNCwiZXhwaXJlc0luIjoiMjAyMi0xMi0wMlQwOToxNjowMi4wMDBaIiwidHlwZSI6MiwiaWF0IjoxNjM4NDQzMzQ0LCJleHAiOjE2Mzg0NDM0MDR9.Ejrq80ClUAVJTku7dpDvXS_OYesOd6lm9XyugeCkI8c

###
POST  http://localhost:4000/api/country/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJGX05BTUUiOiJma3NkZmtsamRza2wiLCJNX05BTUUiOm51bGwsIkxfTkFNRSI6bnVsbCwiTU9CSUxFX05PIjoyMzIzLCJFTUFJTF9JRCI6ImVtYWlsQGVtYWlsLmNvbSIsIlBBUkVOVF9JRCI6bnVsbCwiaWQiOjU1LCJ1c2VyX2lkIjoxNCwiZXhwaXJlc0luIjoiMjAyMi0xMi0wMlQwOToxNjowMi4wMDBaIiwidHlwZSI6MiwiaWF0IjoxNjM4NTE1MDc1LCJleHAiOjE2Mzg2MDE0NzV9.IH-OoJaE98TjJCBLtj4wOxumgL7Ge32JUeWcZqGm6r0

{
    "name":"China",
    "continent":"asia"
}

###
POST  http://localhost:4000/api/country/update HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJGX05BTUUiOiJma3NkZmtsamRza2wiLCJNX05BTUUiOm51bGwsIkxfTkFNRSI6bnVsbCwiTU9CSUxFX05PIjoyMzIzLCJFTUFJTF9JRCI6ImVtYWlsQGVtYWlsLmNvbSIsIlBBUkVOVF9JRCI6bnVsbCwiaWQiOjU1LCJ1c2VyX2lkIjoxNCwiZXhwaXJlc0luIjoiMjAyMi0xMi0wMlQwOToxNjowMi4wMDBaIiwidHlwZSI6MiwiaWF0IjoxNjM4NTE1MDc1LCJleHAiOjE2Mzg2MDE0NzV9.IH-OoJaE98TjJCBLtj4wOxumgL7Ge32JUeWcZqGm6r0

{
    "id":"1",
    "name":"Algeria",
    "continent":"Africa"
}

###
GET  http://localhost:4000/api/country/list 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJGX05BTUUiOiJma3NkZmtsamRza2wiLCJNX05BTUUiOm51bGwsIkxfTkFNRSI6bnVsbCwiTU9CSUxFX05PIjoyMzIzLCJFTUFJTF9JRCI6ImVtYWlsQGVtYWlsLmNvbSIsIlBBUkVOVF9JRCI6bnVsbCwiaWQiOjU1LCJ1c2VyX2lkIjoxNCwiZXhwaXJlc0luIjoiMjAyMi0xMi0wMlQwOToxNjowMi4wMDBaIiwidHlwZSI6MiwiaWF0IjoxNjM4NTE1MDc1LCJleHAiOjE2Mzg2MDE0NzV9.IH-OoJaE98TjJCBLtj4wOxumgL7Ge32JUeWcZqGm6r0